version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: tabi
      POSTGRES_PASSWORD: tabipass
      POSTGRES_DB: tabi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tabi"]
      interval: 1s
      timeout: "5s"
      retries: 10

  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  pgdata: